### ISSUE TITLE
Official SAP support

### ISSUE THREAD

**Issue by desgovedarska** [SAP/PyHDB#100]
Hi guys,
I was wondering if it's ok to note in the Readme.md file that this driver is not the one officially supported by SAP and perhaps add a link to the hdbcli documentation here: https://help.sap.com/viewer/0eec0d68141541d1b07893a39944924e/2.0.02/en-US/f3b8fabf34324302b123297cdbe710f0.html

Just because this will most likely cause some confusion since this is in the SAP namespace.

**Comment by tomslee** [comment]
Hi Des, the timing for this request is good. 

As of today the HANA Client software package is available to non-SAP customers from https://tools.hana.ondemand.com/#hanatools under an SAP developer license. The Client software package includes the hdbcli python driver, so while install is still a bit more difficult than pyhdb it is at least globally available.  I'll suggest some wording to Christoph as soon as I can.

**Comment by desgovedarska** [comment]
Hi Tom,
That sounds great! :)

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project. Please check active maintained alternative: https://pypi.org/project/hdbcli/
