### ISSUE TITLE
cesu8 decode error

### ISSUE THREAD

**Issue by jstorryefx** [SAP/PyHDB#102]
I'm receiving an UnicodeDecodeError error when I try to pull data from HANA using the PyHDB library while iterating through the results in the following code.
```
from sqlalchemy import create_engine
engine = create_engine('hana+pyhdb://%s:%s@%s:%s' % (username, password, host, port))
connection = engine.connect()
result = connection.execute("select * from TASKS")
for row in result.fetchall():
   test = row
connection.close()
```

I've narrowed it down to the following snippet.

```
import pyhdb.cesu8
input = b'\xed\xa0\xbd'
pyhdb.cesu8.decode(input)
```

Which generates the error:

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 0: invalid continuation byte`

Is this the expected behavior? My assumption is that if the data can be stored in HANA we should be able to read it with the library but my knowledge of utf-8/cesu8 is limited.

Thanks,

Jon

**Comment by wadeej** [comment]
I ran into similar issues, mostly when reading in LOB/CLOB/NLOB types.  What I found was that python was having issues decoding latin character with the encode `utf-8` (such as i's with accents).  I have found success using `latin-1` encoding instead of `utf-8` in my own clone `pyhdb` but cannot say with 100% certainty that this will fix all problems of this type.

**Comment by wadeej** [comment]
After a bit more examination it comes down to Python an issue in Python:
When passed in as a `str` object `\xed` has no issues:
```In: '\xed'
Out: 'í'```

However when the input is a `bytes` object `b'\xed`, `utf-8` can't decode the character.  The utf8 version of the `bytes` object is `b'\xc3\xad'`:
```In: 'í'.encode('utf8')
Out: b'\xc3\xad' ```

Finally `'\xed` CAN be decoded as an `í` by using a different codec:
```b'\xed'.decode('ISO-8859-1')
Out[214]: 'í'```

All this to be said, the encoding/decoding issues are a bit complex and it seems like the approach of `pyhdb` does not take into account some of the complexities of the return values.

**Comment by jarus** [comment]
The interesting question is from where the encoded byte string comes. How did you inserted the data into the database via PyHDB or another client e.g. HANA Studio or another database driver?

**Comment by jstorryefx** [comment]
For me, the original data came in via SAP Data Services. To add, if I use the hdbcli python library with the same query there are no errors.

**Comment by wadeej** [comment]
It seems like the trouble is that CESU-8 _SHOULD_ pass in 6 byte long sequence, but what we are running into is at some point SAP Hana is passing just a 3 byte sequence (`b'\xed\xa0\xbd'` in @jstorryefx 's case) and the so the conversion fails.  A 6 byte CESU-8 sequence should correspond to a 4 byte UTF-8 sequence, but I do not know if the same holds try for a 3 byte sequence (i.e. does 3 byte CESU-8 correspond to a 2 byte UTF-8?)

**Comment by jarus** [comment]
Let me summarise the problem:
- `b'\xed\xa0\xbd'` isn't a valid CESU-8 byte sequence as additional 3 bytes are missing for a unicode point. Ether the data is incomplete stored in the database (the SAP HANA product support would be happy to help in that case) or maybe the character/byte sequence is at the end of a LOB and PyHDB's encoding fails in that corner case as it doesn't fetch the missing 3 bytes. @jstorryefx Would it be possible to get the original data as unicode text? You can also send the data directly via mail to [me](mailto:christoph.heer@sap.com). Can you describe the structure of the table? Is the column a `NVARCHAR` or `NCLOB`? Is it a row or column store table? If you retrieve the data with another client e.g. HANA Studio is the tool able to display the full data?
- Until now there is no prove or scenario that shows a bug in PyHDB's CESU decoding or encoding.

**Comment by jstorryefx** [comment]
I had a chance to test the changes today and the issue that I was having has been resolved with  946a0f4 !

Thanks @jarus! and also @wadeej for helping to clarify what the issue was!

**Comment by yuguosen** [comment]
I update my pyhdb to the latest,and test this
`import pyhdb.cesu8
test = b'Should say Professional Designation \xed\xa0\xbd\xed\xb8\x8aThis was in the New Hire PAR'
pyhdb.cesu8.decode(test)`
it's correct,but i still  miss this error when I read  data from hana,here is mycode 
`def get_mat(conn,sql):
    cursor = conn.cursor()
    cursor.execute(sql) 
    mat =cursor.fetchall()
    return mat`
and the error message is
`'utf-8' codec can't decode byte 0xed in position 90: invalid continuation byte`

**Comment by suryalilly** [comment]
I have also updated the pyhdb with the latest version i am getting this error 
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 11: invalid continuation byte

**Comment by Quantum-Sicarius** [comment]
Hi,
I am not sure if I should open a new issue. I am receiving the following:
`    connection = pyhdb.connect(
  File "/home/thomas/.local/lib/python3.9/site-packages/pyhdb/__init__.py", line 30, in connect
    conn.connect()
  File "/home/thomas/.local/lib/python3.9/site-packages/pyhdb/connection.py", line 141, in connect
    agreed_auth_part = self._auth_manager.perform_handshake()
  File "/home/thomas/.local/lib/python3.9/site-packages/pyhdb/auth.py", line 50, in perform_handshake
    response = self.connection.send_request(request)
  File "/home/thomas/.local/lib/python3.9/site-packages/pyhdb/connection.py", line 83, in send_request
    payload = message.pack()  # obtain BytesIO instance
  File "/home/thomas/.local/lib/python3.9/site-packages/pyhdb/protocol/message.py", line 55, in pack
    self.build_payload(payload)
  File "/home/thomas/.local/lib/python3.9/site-packages/pyhdb/protocol/message.py", line 45, in build_payload
    segment.pack(payload, commit=self.autocommit)
  File "/home/thomas/.local/lib/python3.9/site-packages/pyhdb/protocol/segments.py", line 94, in pack
    self.build_payload(payload)
  File "/home/thomas/.local/lib/python3.9/site-packages/pyhdb/protocol/segments.py", line 80, in build_payload
    part_payload = part.pack(remaining_size)
  File "/home/thomas/.local/lib/python3.9/site-packages/pyhdb/protocol/parts.py", line 103, in pack
    arguments_count, payload = self.pack_data(remaining_size - self.header_size)
  File "/home/thomas/.local/lib/python3.9/site-packages/pyhdb/protocol/parts.py", line 591, in pack_data
    payload = Fields.pack_data(fields)
  File "/home/thomas/.local/lib/python3.9/site-packages/pyhdb/protocol/parts.py", line 48, in pack_data
    field = field.encode('cesu-8')
LookupError: unknown encoding: cesu-8
`

This is executing on  pyhdb.connect()

**Comment by amarvin** [comment]
> Hi,
> I am not sure if I should open a new issue. I am receiving the following:
> 
> ```
>     connection = pyhdb.connect(
>   File "/home/thomas/.local/lib/python3.9/site-packages/pyhdb/__init__.py", line 30, in connect
>     conn.connect()
>   File "/home/thomas/.local/lib/python3.9/site-packages/pyhdb/connection.py", line 141, in connect
>     agreed_auth_part = self._auth_manager.perform_handshake()
>   File "/home/thomas/.local/lib/python3.9/site-packages/pyhdb/auth.py", line 50, in perform_handshake
>     response = self.connection.send_request(request)
>   File "/home/thomas/.local/lib/python3.9/site-packages/pyhdb/connection.py", line 83, in send_request
>     payload = message.pack()  # obtain BytesIO instance
>   File "/home/thomas/.local/lib/python3.9/site-packages/pyhdb/protocol/message.py", line 55, in pack
>     self.build_payload(payload)
>   File "/home/thomas/.local/lib/python3.9/site-packages/pyhdb/protocol/message.py", line 45, in build_payload
>     segment.pack(payload, commit=self.autocommit)
>   File "/home/thomas/.local/lib/python3.9/site-packages/pyhdb/protocol/segments.py", line 94, in pack
>     self.build_payload(payload)
>   File "/home/thomas/.local/lib/python3.9/site-packages/pyhdb/protocol/segments.py", line 80, in build_payload
>     part_payload = part.pack(remaining_size)
>   File "/home/thomas/.local/lib/python3.9/site-packages/pyhdb/protocol/parts.py", line 103, in pack
>     arguments_count, payload = self.pack_data(remaining_size - self.header_size)
>   File "/home/thomas/.local/lib/python3.9/site-packages/pyhdb/protocol/parts.py", line 591, in pack_data
>     payload = Fields.pack_data(fields)
>   File "/home/thomas/.local/lib/python3.9/site-packages/pyhdb/protocol/parts.py", line 48, in pack_data
>     field = field.encode('cesu-8')
> LookupError: unknown encoding: cesu-8
> ```
> 
> This is executing on pyhdb.connect()

Same for me. My inputs to `pyhdb.connect()` are pretty simple characters (numbers, upper and lower case letters without accents, dashes, periods, underscores) but I get this error.

**Comment by darveshsingh** [comment]
Same for me: Statement executed -> pyhdb.connect()
Error message -> unknown encoding: cesu-8
Python version -> 3.9

**Comment by jweston18** [comment]
I am having the same issue as @amarvin and @darveshsingh and receive the cesu-8 error with pyhdb.connect(). I have no accents or encoded chars in the input parameters.

Code:
```python
import pyhdb
conn = pyhdb.connect(host = 'host01',
                                  port = 123,
                                  user = 'user',
                                  password = 'password1!')
```

Output:
```python
LookupError: unknown encoding: cesu-8
```

3 most recent calls:
```python
...\pyhdb\protocol\parts.py in pack(self, remaining_size)
    101     def pack(self, remaining_size):
    102         """Pack data of part into binary format"""
--> 103         arguments_count, payload = self.pack_data(remaining_size - self.header_size)
    104         payload_length = len(payload)
    105 

...\pyhdb\protocol\parts.py in pack_data(self, remaining_size)
    589             fields = fields + list(method_data)
    590 
--> 591         payload = Fields.pack_data(fields)
    592         return 1, payload
    593 

...\pyhdb\protocol\parts.py in pack_data(fields)
     46         for field in fields:
     47             if is_text(field):
---> 48                 field = field.encode('cesu-8')
     49 
     50             size = len(field)
```

Python = 3.9.2

**Comment by darveshsingh** [comment]
> I am having the same issue as @amarvin and @darveshsingh and receive the cesu-8 error with pyhdb.connect(). I have no accents or encoded chars in the input parameters.
> 
> Code:
> 
> ```python
> import pyhdb
> conn = pyhdb.connect(host = 'host01',
>                                   port = 123,
>                                   user = 'user',
>                                   password = 'password1!')
> ```
> 
> Output:
> 
> ```python
> LookupError: unknown encoding: cesu-8
> ```
> 
> 3 most recent calls:
> 
> ```python
> ...\pyhdb\protocol\parts.py in pack(self, remaining_size)
>     101     def pack(self, remaining_size):
>     102         """Pack data of part into binary format"""
> --> 103         arguments_count, payload = self.pack_data(remaining_size - self.header_size)
>     104         payload_length = len(payload)
>     105 
> 
> ...\pyhdb\protocol\parts.py in pack_data(self, remaining_size)
>     589             fields = fields + list(method_data)
>     590 
> --> 591         payload = Fields.pack_data(fields)
>     592         return 1, payload
>     593 
> 
> ...\pyhdb\protocol\parts.py in pack_data(fields)
>      46         for field in fields:
>      47             if is_text(field):
> ---> 48                 field = field.encode('cesu-8')
>      49 
>      50             size = len(field)
> ```
> 
> Python = 3.9.2

Had to rollback to using Python 3.6

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project. Please check active maintained alternative: https://pypi.org/project/hdbcli/
