### ISSUE TITLE
Executing Graph 

### ISSUE THREAD

**Issue by lscheinman77SAP** [SAP/PyHDB#104]
Cursor.py throws a syntax error when running some queries. The statements can be copied and pasted into HANA studio and executed properly but in this case not. This occurs when running graph procedures that include the CREATE statement and xml such as the following:
('\n'
 '\n'
 '        DROP PROCEDURE "GREEK_MYTHOLOGY"."NEIGHBORS_WITH_RESIDENCE";\n'
 '        \n'
 '        CREATE PROCEDURE "GREEK_MYTHOLOGY"."NEIGHBORS_WITH_RESIDENCE" (OUT '
 'cnt INT)\n'
 '         LANGUAGE GRAPH READS SQL DATA AS\n'
 '          BEGIN\n'
 '                Graph g = Graph("GREEK_MYTHOLOGY", "GRAPH");\n'
 "                Vertex chaos = Vertex(:g, 'Chaos');\n"
 '                Multiset<Vertex> neighbors = Neighbors(:g,:chaos, 0, 2);\n'
 '                Multiset<Vertex> neighborsWithResidence = Multiset<Vertex> '
 '(:g);\n'
 '                FOREACH n IN :neighbors {\n'
 '                        if (:n."RESIDENCE" IS NOT NULL) {\n'
 '                                neighborsWithResidence = '
 ':neighborsWithResidence UNION {:n};\n'
 '                        }\n'
 '                }\n'
 '                cnt = INT(COUNT(:neighborsWithResidence));\n'
 '          END;\n'
 '        \n'
 '        -- the result here is 2, only these are neighbors of Chaos with '
 'residence not null\n'
 '        CALL "GREEK_MYTHOLOGY"."NEIGHBORS_WITH_RESIDENCE"(?);\n'
 '        ')
pyhdb.exceptions.DatabaseError: sql syntax error: incorrect syntax near "CREATE": line 5 col 9 (at pos 89)

**Comment by jarus** [comment]
Did you try to execute the collection of multiple statement as one `cursor.execute`? This isn't possible and you have to execute separately.

**Comment by lscheinman77SAP** [comment]
That did it. Sorry for the bother.

**Comment by jarus** [comment]
No problem. :)
