### ISSUE TITLE
Regex based SQL queries

### ISSUE THREAD

**Issue by ankitjha97** [SAP/PyHDB#106]
Are regex based SQL queries supported by PYHDB?
I am getting an error while executing this query
`cursor.execute(" SELECT ATTRIBUTE_VALUE FROM PARSING2 WHERE (ATTRIBUTE_NAME NOT REGEXP \"^ADDITIONAL\") ")`

The error is:

> sql syntax error: incorrect syntax near "REGEXP": line 1 col 65 (at pos 65)

In case if syntax error what should be correct syntax?

These are the alternate syntax which I have tried:
`cursor.execute(" SELECT ATTRIBUTE_VALUE FROM PARSING2 WHERE \(ATTRIBUTE_NAME NOT REGEXP \"^ADDITIONAL\"\) ")`

`cursor.execute(" SELECT ATTRIBUTE_VALUE FROM PARSING2 WHERE (ATTRIBUTE_NAME NOT REGEXP \"\^ADDITIONAL\") ")`

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project. Please check active maintained alternative: https://pypi.org/project/hdbcli/
