### ISSUE TITLE
Encrypt the connection to HANA Service instance

### ISSUE THREAD

**Issue by sarthak0403** [SAP/PyHDB#107]
Hi,

We're working on an application to be deployed on SCP CF environment. We've SAP HANA Service instance there which requires the connection to be encrypted. I explored the DBAPI a bit and found out that we can use a parameter named 'encrypt' while connecting to the service instance. However, this parameter is not supported in this PyHDB library.  Here's the connection string we're using:

pyhdb.connect(host=host, port=port, user=user, password=pwd, encrypt='true')

When I use the above connection string, I get the following error:

TypeError: connect() got an unexpected keyword argument 'encrypt'
--
 
However, without the 'encrypt' parameter, it works fine. Is it possible to encrypt or enforce SSL while connecting to HANA service instance in PyHDB?

Kind Regards,
Sarthak

**Comment by sarthak0403** [comment]
Hi,

I've found a solution. I'm extending the connection class and modifying the _open_socket_and_init_protocoll() method as follows:

```
def _open_socket_and_init_protocoll(self):
        # CREATE SOCKET
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(10)

        # SSL Context
        context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
        # context.options |= ssl.OP_NO_TLSv1 | ssl.OP_NO_TLSv1_1  # optional
        context.verify_mode = ssl.CERT_NONE
        context.set_default_verify_paths()

        # WRAP SOCKET
        self._socket = context.wrap_socket(sock, server_hostname=self.host)

        # self._socket = wrappedSocket.create_connection((self.host, self.port), self._timeout)
        self._socket.connect((self.host, self.port))

        # Initialization Handshake
        self._socket.sendall(INITIALIZATION_BYTES)

        response = self._socket.recv(8)
        if len(response) != 8:
            raise Exception("Connection failed")

        self.product_version = version_struct.unpack(response[0:3])
        self.protocol_version = version_struct.unpack_from(response[3:8])
```

Can you please review it and let me know if this is fine from security perspective? It's working fine and connecting to the DB using SSL. Just need a confirmation that it's following security best practices.

Kind Regards,
Sarthak

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project. Please check active maintained alternative: https://pypi.org/project/hdbcli/
