### ISSUE TITLE
How to get Huge data from HANA Database/ or can i directly download csv file using python

### ISSUE THREAD

**Issue by shabir1** [SAP/PyHDB#108]
Using pyhdb For large data i am getting below error:
('Not able to retrieve data', DatabaseError(u'internal error: Remote execution error exception 1000002: Allocation failed ; $size$=33554432; $name$=itab; $type$=pool; $inuse_count$=13936; $allocated
_size$=5032699992\n for query)
is there any other way to get large bach data from hana. (e.g streaming)

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project. Please check active maintained alternative: https://pypi.org/project/hdbcli/
