### ISSUE TITLE
Encoding errors

### ISSUE THREAD

**Issue by wadeej** [SAP/PyHDB#109]
https://github.com/SAP/PyHDB/blob/826539d06b8bcef74fe755e7489b8a8255628f12/pyhdb/protocol/lobs.py#L274

Would it be possible to add an option whenever decoding the retrieved information to all for erring character to be "ignored" or "replaced" (https://www.tutorialspoint.com/python/string_decode.htm).  I don't have control over the data source that I am retrieving information out of, but it contains characters that err, when they are decoded with utf-8.  It would be nice to have an option to ignore the erring character, but still be able to read in the remainder of the text.  I know this probably shouldn't be the default functionality, but in the case where I don't have control over the ETL of what makes it into the DB, but I still want the data, this sort of option would be vary helpful.

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project. Please check active maintained alternative: https://pypi.org/project/hdbcli/
