### ISSUE TITLE
Encoding nclobs

### ISSUE THREAD

**Issue by wadeej** [SAP/PyHDB#110]
https://github.com/SAP/PyHDB/blob/826539d06b8bcef74fe755e7489b8a8255628f12/pyhdb/protocol/lobs.py#L260

I believe that nclobs should be encoded using CESU8, which I believe pyhdb has a utility function to encoded data as.  Would it be beneficial to use this encoding here?

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project. Please check active maintained alternative: https://pypi.org/project/hdbcli/
