### ISSUE TITLE
ConnectionRefusedError

### ISSUE THREAD

**Issue by veeraa83** [SAP/PyHDB#111]
When I try to connect to HANA using this package, I get the below error.
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
 Do I need to make configurational changes in the HANA server to allow the connection. Was able to connect via SAP GUI using the same credentials.

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project. Please check active maintained alternative: https://pypi.org/project/hdbcli/
