### ISSUE TITLE
The stored procedure example doesn't work

### ISSUE THREAD

**Issue by timmue** [SAP/PyHDB#117]
The merge-request #98 changed the behavior of accessing the parameters in a way that the example for a stored procedure is not working anymore.
If I revert it, the example works fine for me.
I think the problem here is that the parameter object is getting accessed via an index.
`row_params = [self.ParamTuple(p.id, p.datatype, p.length, parameters[i]) for i, p in enumerate(self._params_metadata)]`
But in the example the parameters are created with a dictionary.
`params = {'A':2, 'B':5, 'C':None, 'D': None}`

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project. Please check active maintained alternative: https://pypi.org/project/hdbcli/
