### ISSUE TITLE
issue with where clause

### ISSUE THREAD

**Issue by jochensteinmetz** [SAP/PyHDB#122]
The following query worked
query="select DISTINCT <column name> from <table name>"

What is the right notation to get a where clause work:
1. query='select * from <table name> where <column name> = " any string with blanks" '
2. query="select * from <table name> where <column name> = 'any string with blanks'"
3. query='select * from <table name> where <column name> = \" any string with blanks\" '
4. query="select * from <table name> where <column name> = \' any string with blanks\'"

1.-4. did not work for me.
for 1. I get the error pyhdb.exceptions.DatabaseError: invalid column name:

**Comment by jarus** [comment]
This is expected behavior. SAP HANA‘s SQL dialect only expect double quotes for colum names to allow names with spaces or other special characters.
