### ISSUE TITLE
Connect to SAP HaaS database with direct sql port

### ISSUE THREAD

**Issue by BigNuoLi** [SAP/PyHDB#123]
Does the PyHDB driver support connect to SAP HaaS database with direct sql  host/port pair ?
Here I got error "**pyhdb.exceptions.DatabaseError: only secure connections are allowed**" as I did not find where to pass the secure parameters in pyhdb.connect(....).

**Comment by sarthak0403** [comment]
Hi BigNuoLi, I was struggling with same issue but looks like they haven't made it compatible with HaaS yet. I've found workaround here: https://github.com/SAP/PyHDB/issues/107

**Comment by BigNuoLi** [comment]
Hi, sarthak0403, 
Thanks a lot.
I follow your solution to change my forked codes, and I can access my HaaS DB now.
👍
