### ISSUE TITLE
Hana warnings are treated as error

### ISSUE THREAD

**Issue by isansahoo123** [SAP/PyHDB#130]
Hello,
We are trying to execute procedure via pyHDB and in that procedure it has some DDL statements. As a result Hana gives warning message like:

`java.sql.SQLWarning: Not recommended feature: DDL statement is used in Dynamic SQL (current dynamic_sql_ddl_error_level = 1)`

But this warning message is treated as error and code goes into the exception block and stops the process. What is the workaround here?

**Comment by isansahoo123** [comment]
@jarus could you please help us here?

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project. Please check active maintained alternative: https://pypi.org/project/hdbcli/
