### ISSUE TITLE
Using PYHDB library a RAW Column Store Data Type in HANA DB is read as binary object

### ISSUE THREAD

**Issue by mike1130694** [SAP/PyHDB#134]
I've been using the PYHDB library to extract from HANA DB tables.

However I noticed that column "MSGGUID" was read as a binary object by the library. Originally the Column Store Data Type in HANA Studio is "RAW".
![image](https://user-images.githubusercontent.com/15694432/77894508-aa2c6e00-7275-11ea-9e78-8cfb49772cf6.png)

In the pandas Dataframe where I've extracted the dataset. this is how the column is shown

![image](https://user-images.githubusercontent.com/15694432/77894521-b1537c00-7275-11ea-91c4-0f42d0c18ee1.png)

I've been trying to decode this column to transform it to a string since I want to perform certain operations like join using this ID.

I wonder if anyone has faced this situation and whether you could give me some suggestion on how to decode this binary object.

I would appreciate any information you could provide.

Sincerely,

Miguel Angel Meza Martinez

**Comment by amosang** [comment]
@mike1130694 
I ran into this issue, particularly for GUIDs, which occur in tables like BUT000. My work-around for this issue is to examine each column of the df, and if it is of type "byte", then to convert it to a string as shown in the code snippet below.

I wish that pyhdb can auto-magically take care of this isssue, nonetheless.

Hope this helps. 

```
# Use first row of df as representative, to look for byte strings to convert. Assumption is that all byte strings are hex-encoded.
        for col_name in df.columns:
            if isinstance(df.loc[0, col_name], bytes):
                df[col_name] = df[col_name].apply(lambda x: bytes.hex(x))  # Convert hex-encoded byte string to string.
        return df
```

**Comment by mike1130694** [comment]
Thanks a lot. The missing part that I had was "bytes.hex(x)" I've tried the "decode" function.

I looked for a similar solution but couldn't find it. 
Closing the issue since this helps me transform the bytes object to a string
