### ISSUE TITLE
Connection.Query.fetchmany silently returns nothing if batchsize is too large

### ISSUE THREAD

**Issue by amarvin** [SAP/PyHDB#136]
If a very large batchsize is requested for fetching results of a query, no exception is raised, yet no results are returned even if the query would return results with a smaller batchsize.
```python
>>> conn = pyhdb.connect(**credentials)
>>> cur = conn.cursor()
>>> query = 'SELECT * FROM BLAH...'
>>> cur.execute(query)
>>> cur.fetchmany()
[...]  # tons of results
>>> cur.execute(query)
>>> cur.fetchmany(size=1000000000)
[]
```

Does HANA return an error message that maybe `pyrfc` should raise as an exception?

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project. Please check active maintained alternative: https://pypi.org/project/hdbcli/
