### ISSUE TITLE
Getting syntex error 

### ISSUE THREAD

**Issue by achaube2** [SAP/PyHDB#137]
Hi 

I was trying to run query 

but getting 
pyhdb.exceptions.DatabaseError: sql syntax error: incorrect syntax near "-": line 1 col 11043 (at pos 11043)

please help me to resolve

**Comment by achaube2** [comment]
sample query - 

SELECT 
 BARK."KUNAG" AS "SoldTo",
SUM(VBPP."NETWR") AS "NetValue"
FROM
 "_SYS_BIC"."XYZ-ABC.profitability/S_CA_R_BillingDocument" VBPP
INNER JOIN "_SYS_BIC"."XYZ-ABC.profitability/S_CA_R_BillingDocumentItem" VBPP
  ON VBRK."VBELN" = VBRP."VBELN"
WHERE 
 VBRK."FKDAT" >= '20190824' AND VBRK."FKDAT" <= '20190927'
"

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project. Please check active maintained alternative: https://pypi.org/project/hdbcli/
