### ISSUE TITLE
Header unpacking problem with the number of bytes (less than 32).

### ISSUE THREAD

**Issue by AFGhazy** [SAP/PyHDB#146]
Data is not consistent with the struct header, it does expect 32 bytes in the header unpack but sometimes it does return single byte+ (all the way to 31), this happens whenever we are making a query that fetches millions of records, in case of small queries (couple of thousands), this problem doesn't occur.

`
header = MessageHeader(*cls.header_struct.unpack(raw_header))
`
https://github.com/SAP/PyHDB/blob/master/pyhdb/protocol/message.py#L105

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project. Please check active maintained alternative: https://pypi.org/project/hdbcli/
