### ISSUE TITLE
NCLOB Size Limitation while Calling Procedure

### ISSUE THREAD

**Issue by srikanthpdpl** [SAP/PyHDB#148]
While calling Procedure GET_OBJECT_DEFINITION we have the output parameter OBJECT_CREATION_STATEMENT which will return the creation statement for any object passed to procedure. 
The result of OBJECT_CREATIOB_STATEMENT is truncated to 1008 chars. We don't have option to limit the LOB Column Size.

**Comment by rybafish** [comment]
just curious, do you do .read() to extract the full value of the lob object?

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project. Please check active maintained alternative: https://pypi.org/project/hdbcli/
