### ISSUE TITLE
Cannot connect on Windows 64bit

### ISSUE THREAD

**Issue by TwoLaid** [SAP/PyHDB#2]
When trying to connect on Windows 64bit with either 32bit or 64bit Python 2.7, the client just blocks indefinitely because it is stuck on a `recv` call. It is waiting on the server's answer on the AUTHENTICATE message.

This is due to the fact that you are using this struct for the Message header: 

    struct = struct.Struct('liIIhb9B')

The first parameter is the session ID, which is supposed to be I8 (8 byte integer). But the `l` you are using here only produces a 4 byte integer on 64bit Windows. If you change this to `q` it works just fine on Windows, and I have tested this on Linux as well.

**Comment by bsrdjan** [comment]
Thanks @TwoLaid, fixed.
