### ISSUE TITLE
Support of binary locator (type 31)

### ISSUE THREAD

**Issue by mathebox** [SAP/PyHDB#33]
I want to perform multiple inserts with a prepared statement. The table definition contains a column of `ST_POINT`. On execution I get the following error:
```bash
InterfaceError: Prepared statement parameter datatype not supported: 31
```
It there any documentation available that would help me to add this feature? Or do you plan to implement it in the near future?

**Comment by jarus** [comment]
Currently there is no support for the Geo/GIS Datatypes of SAP HANA in PyHDB. You are welcome to implement them. The binary format is defined in the HANA Network Command Protocol Document and you can look at the other datatypes in PyHDB to get a idea how to implement them.

Christoph

**Comment by mathebox** [comment]
Please have a look at this pull request #34
