### ISSUE TITLE
Create stored procedure PROC_ADD2 in unit test

### ISSUE THREAD

**Issue by ralhei** [SAP/PyHDB#39]
@bsrdjan 
Can you create the above mentioned stored procedure when running 'test_call_stored.py' (as a fixture)? 
Otherwise this unit tests will fail for users running tests on HCP or their own Hana instance as this stored procedure does of course not exist in those DBs. 
Thanks!

**Comment by jarus** [comment]
Fixed by a3f57d0cbca63da5d49650fb0896f94a058ff3ce.
