### ISSUE TITLE
Error using pyhdb: File "/usr/lib/python2.6/site-packages/pyhdb-0.2.3-py2.6.egg/pyhdb/__init__.py", line 71

### ISSUE THREAD

**Issue by seansilvestri** [SAP/PyHDB#41]
File "/usr/lib/python2.6/site-packages/pyhdb-0.2.3-py2.6.egg/pyhdb/__init__.py", line 71
    clean_params = {'%s' % rm_hana_prefix(key): val for key, val in params.iteritems()}

I get this with the latest code as well as 0.2.3 release.
Running on Centos 6.5. Please advise.

**Comment by ralhei** [comment]
Yes, we are aware of this problem, Python 2.6  is not supported in the moment (even though the docs claim it is). We are currently evaluating whether we continue 2.6 support or not. 
The best current option is to use Python 2.7. Sorry for the inconvenience this might cause.

**Comment by seansilvestri** [comment]
Please be so kind and update your docs, I wasted a lot of my time with this...
