### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 5915: character maps to <undefined>

### ISSUE THREAD

**Issue by levinanton** [SAP/PyHDB#42]
Maybe an issue is not related to PyHDB.

When installing with pip I get the following: 

------------------------------------------------------------
C:\Python34\Scripts\pip run on 06/15/15 15:34:00
Downloading/unpacking pyhdb
  Getting page https://pypi.python.org/simple/pyhdb/
  URLs to search for versions for pyhdb:
  * https://pypi.python.org/simple/pyhdb/
  Analyzing links from page https://pypi.python.org/simple/pyhdb/
    Found link https://pypi.python.org/packages/source/p/pyhdb/pyhdb-0.1.0.tar.gz#md5=8ab853959eeba0320c8345106b0b331b (from https://pypi.python.org/simple/pyhdb/), version: 0.1.0
    Found link https://pypi.python.org/packages/source/p/pyhdb/pyhdb-0.2.2.zip#md5=d4e1bc9d2384a057bd9ee589df7763f2 (from https://pypi.python.org/simple/pyhdb/), version: 0.2.2
    Found link https://pypi.python.org/packages/source/p/pyhdb/pyhdb-0.2.3.tar.gz#md5=bb9ee84f88ff8c94b84b7904a63fc037 (from https://pypi.python.org/simple/pyhdb/), version: 0.2.3
  Using version 0.2.3 (newest of versions: 0.2.3, 0.2.2, 0.1.0)
  Downloading from URL https://pypi.python.org/packages/source/p/pyhdb/pyhdb-0.2.3.tar.gz#md5=bb9ee84f88ff8c94b84b7904a63fc037 (from https://pypi.python.org/simple/pyhdb/)
  Running setup.py (path:C:\Users\<USERNAME>\AppData\Local\Temp\pip_build_<USERNAME>\pyhdb\setup.py) egg_info for package pyhdb
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "C:\Users\<USERNAME>\AppData\Local\Temp\pip_build_<USERNAME>\pyhdb\setup.py", line 40, in <module>
        long_description=get_long_description(),
      File "C:\Users\<USERNAME>\AppData\Local\Temp\pip_build_<USERNAME>\pyhdb\setup.py", line 28, in get_long_description
        return readme.read()
      File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 5915: character maps to <undefined>
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "C:\Users\<USERNAME>\AppData\Local\Temp\pip_build_<USERNAME>\pyhdb\setup.py", line 40, in <module>

    long_description=get_long_description(),

  File "C:\Users\d053601\AppData\Local\Temp\pip_build_D053601\pyhdb\setup.py", line 28, in get_long_description

    return readme.read()

  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode

    return codecs.charmap_decode(input,self.errors,decoding_table)[0]

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 5915: character maps to <undefined>

**Comment by ralhei** [comment]
I fails when the README.rst is read by setup.py which cannot handle those unicode values used for the LOB examples. 
We probably have to provide an decoding parameter when reading the file. I try to fix this asap.

**Comment by levinanton** [comment]
Hi @ralhei Thanks for your reply. For now I cloned the repo and removed all the texts from README before installation. But afterwards I experienced 2 more issues. File cursor.py, line #35 and #265 syntax error TypeError, msg should be TypeError as msg and when importing pyhdb there is an ImportError: No module named 'ConfigParser' because in Python 3 it was renamed to configparser

A question. Do you plan Python 3 support or should I switch to older version for now?

**Comment by ralhei** [comment]
yes, this is another Py3 problem not fixed yet (report at #36). Unfortunately we had some tough time constraints to provide 2.7 support for pyHDB so that Py 2.6 and Py 3.x is currently not properly working. We know that we have to fix this but haven't got around to do so, I'm afraid to say.

**Comment by levinanton** [comment]
UnicodeDecodeError is not reproducible with Python 2.7 
I will close that for now
