### ISSUE TITLE
New release and PyPI update

### ISSUE THREAD

**Issue by xchrdw** [SAP/PyHDB#44]
Please create a new release and upload it to PyPI as the current version there is 0.2.3.

**Comment by jaheba** [comment]
Stil not updated to 0.3.0

**Comment by ralhei** [comment]
Unfortunately it is not clear who is currently maintaining pyhdb (and hence is responsible for releases), so for now we have to live with checking out the code from github directly. But I hope that this will be sorted out soon ...
