### ISSUE TITLE
Some sql 'case' statements fail with numeric parameter substitution

### ISSUE THREAD

**Issue by ralhei** [SAP/PyHDB#46]
Change 9dc77f6 (using paramstyle 'numeric' over 'format') seems to cause problems with same sql 'case' statements when containing parameter substitution:

```
query = '''
SELECT DISTINCT group_id,
                max(CASE
                    WHEN m.name = 'Aaron' THEN 4
                    WHEN m.name = 'Ronald' THEN 3
                    WHEN m.name = 'Jack' THEN 2
                    ELSE 0
                END)
FROM sa_example_main m
GROUP BY m.group_id
ORDER BY max(CASE
    WHEN m.name = 'Aaron' THEN 4
    WHEN m.name = 'Ronald' THEN 3
    WHEN m.name = 'Jack' THEN 2
    ELSE :1
END) DESC
'''
params = (0, )
cur.execute(query, params)
```

results in:

```
pyhdb.exceptions.DatabaseError: invalid column name: not included in SELECT DISTINCT column list: M.NAME: line 12 col 10 (at pos 317)
```

If 'paramstyle' equals 'format'  (or the :1 in the else statement is replaced with '0') then the command succeeds.

**Comment by jarus** [comment]
Actually I think that isn't a PyHDB problem. If someone else run into the issue then we should verify that this SQL is valid regardless of the client.
