### ISSUE TITLE
stored procedures: table as output

### ISSUE THREAD

**Issue by jaheba** [SAP/PyHDB#50]
## What should work

It is possible to have tables as an output argument for stored procedures:

``` sql
create procedure PROC_DUMMY (in a int, in b int, out c int, out d DUMMY, out e TABLES)
  language sqlscript
  reads sql data as
  begin
    c := :a + :b;
    d = select * from DUMMY;
    e = select * from TABLES;
  end
```
## Why it fails

Currently calling such a stored procedure fails, since the number of arguments the database expects is 2 but pyhdb expects 4:

``` python
# Cursor.next
if len(parameters) != len(self._params_metadata):
    raise ProgrammingError("Prepared statement parameters expected %d supplied %d." %
                           (len(self._params_metadata), len(parameters)))
```

Removing this check unveils a second issue. It is possible for one cursor to access several result sets. The above example provides three table like results. `c` is send via `OutputParameters` and made available through `fetchmany` by setting `self._buffer` to these values. The other two (`d` and `e`) are proper result sets. Though `e` never gets fetched since pyhdb assumes that every cursor only operates on one result set. Falsely it believes that having finished `d` there is no work left to do.

``` python
#Cursor.fetchmany
     request = RequestMessage.new(
            self.connection,
            RequestSegment(
                message_types.FETCHNEXT,
                (ResultSetId(self._resultset_id), FetchSize(size - cnt))
            )
        )
```
## How to fix

There are two issues to tackle. The easy one is to fix the expectation that the `len` of expected parameters by the database is the same as the provided one.

Now to the hard one:

Using `cursor.execute_prepared` is bad. Python's `dbapi` proposes the use of `.callproc` instead. The problem is that the return value of a normal SQL query is a single table, whilst stored procedures can provide zero to many tables. Instead `callproc` could return two values, a collection of the scalar values and a collection of tables. Both can be empty.

``` python
values, tables = cursor.callproc('PROC_DUMMY')
```

Further support for multiple result sets per cursor has to be implemented.

Inform: @mathebox

**Comment by Vigneshbosch** [comment]
Hi jaheba,

Please suggest a best way to insert around 10 million into Hana Table . Is it possible to pass a data frame as a parameter for a Stored procedure call ??

Thanks in advance

Regards
Vignesh J

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project. Please check active maintained alternative: https://pypi.org/project/hdbcli/
