### ISSUE TITLE
PyHDB does not install for Python 3

### ISSUE THREAD

**Issue by mastram** [SAP/PyHDB#54]
Hi, 
The command : `$ pip install pyhdb` installs it only for Python 2.x

On my Raspberry Pi I have both Python 2 and 3. 
The example code works on Python 2 but does not work in Python 3. It says : "No module named pyhdb"

How can we easily install it for Python 3 ?

**Comment by jarus** [comment]
I think you have to use `pip3` which should install PyHDB for Python 3.
