### ISSUE TITLE
MemoryError in connect

### ISSUE THREAD

**Issue by mschmill** [SAP/PyHDB#55]
I have used PyHDB successfully to connect to a HANA database. I am currently trying to connect to a different database and I get a MemoryError:

```
>>> import pyhdb
>>> pyhd.connect(host='xxx',port=xxxx,user='xxxx',password='xxxxxx')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/etc/lib64/anaconda/lib/python2.7/site-packages/pyhdb/__init__.py", line 30, in connect
    conn.connect()
  File "/etc/lib64/anaconda/lib/python2.7/site-packages/pyhdb/connection.py", line 141, in connect
    agreed_auth_part = self._auth_manager.perform_handshake()
  File "/etc/lib64/anaconda/lib/python2.7/site-packages/pyhdb/auth.py", line 50, in perform_handshake
    response = self.connection.send_request(request)
  File "/etc/lib64/anaconda/lib/python2.7/site-packages/pyhdb/connection.py", line 84, in send_request
    return self.__send_message_recv_reply(payload.getvalue())
  File "/etc/lib64/anaconda/lib/python2.7/site-packages/pyhdb/connection.py", line 107, in __send_message_recv_reply
    _payload = self._socket.recv(header.payload_length - payload.tell())
MemoryError
```

Any idea what this failure means?

**Comment by ralhei** [comment]
Hmm, as far as I know a MemoryError is raised when Python cannot allocate enough memory when creating a new object. Would be interesting to know what the value of `header.payload_length` and `payload.tell()` are, must be massive ... 
For enabling debugging, can you run this before establishing the connection to hana:
```
import logging
log = logging.getLogger('receive')
log.setLevel(logging.DEBUG)
log.addHandler(logging.StreamHandler())
```
This should print out some useful information.

**Comment by mschmill** [comment]
@ralhei thanks for your quick reply! i thought it was a strange error message. it turned out that the port that i was given was incorrect. i do not know what is listening on that port but it's not httpd or tomcat because those will eventually produce a connection refused and not a MemoryError.

**Comment by shabir1** [comment]
@ralhei how i get huge data from hana using pyhdb 
Using pyhdb For large data i am getting below error:
('Not able to retrieve data', DatabaseError(u'internal error: Remote execution error exception 1000002: Allocation failed ; $size$=33554432; $name$=itab; $type$=pool; $inuse_count$=13936; $allocated
_size$=5032699992\n for query)
is there any other way to get large bach data from hana. (e.g streaming)
