### ISSUE TITLE
How to fetch data from HANA in Python in table format

### ISSUE THREAD

**Issue by trmanish** [SAP/PyHDB#59]
Hi 

I have installed the Pyhdb and everything correctly. However the problem I see is that everytime i need to fetch the data it comes as a tuple. I want to fetch the data as a pandas dataframe. Like in Postgressql if I connect it with Python and use an adapter called pysopg2 on the connection object like below: 

`Creating database connection string
In [9]:
USER_CRED_FILE = os.path.join(os.path.expanduser('~'), '.dslab_user.cred')
def fetchDBCredentials(dbcred_file=USER_CRED_FILE):
    """
       Read database access credentials from the file in $HOME/.ipynb_dslab.cred
    """
    #Read database credentials from user supplied file
    conf = ConfigParser.ConfigParser()
    conf.read(dbcred_file)
    #host, port, user, database, password
    host = conf.get('database_creds','host')
    port = conf.get('database_creds','port')
    user = conf.get('database_creds','user')
    database = conf.get('database_creds','database')
    password = conf.get('database_creds','password')

```
#Initialize connection string
conn_str =  """dbname='{database}' user='{user}' host='{host}' port='{port}' password='{password}'""".format(                       
                database=database,
                host=host,
                port=port,
                user=user,
                password=password
        )
return conn_str
```

Create a connection object to the database
In [10]:
conn = psycopg2.connect(fetchDBCredentials())

`

Then I can simply run 

conn.commit 

or I can do 

psql.read_sql(sql,conn) 

and it would get the result in table format. 

Please see the below two links to get a sense what I am asking. 

[https://github.com/vatsan/gp_jupyter_notebook_templates/blob/master/notebooks/00_database_connectivity_setup.ipynb](url)

[https://github.com/vatsan/gp_jupyter_notebook_templates](url)

How do I get that in HANA. Something similar to Pyscopg2 I guess?

**Comment by ralhei** [comment]
Hi Manish,
      
      the HANA python database adapter basically implements the db API
      as specified in https://www.python.org/dev/peps/pep-0249/
      This does not include any extensions to some other 3rd party
      python package, like pandas, numpy, or any of the many others. 
      
      The fact that psycopg2 returns pandas objects is a pure
      (non-standard) extension of psycopg2 and is most probably not
      implemented in most of the other python db adapters (like
      cx_oracle, sqlite, etc.). If you wish to turn result tuples from
      pyhdb into pandas objects you unfortunately have to do this
      yourself through an additional conversion step. 
      
      Ralph
      
      On 05/03/2016 08:39 PM, Manish wrote:
    
    
      Hi 
      I have installed the Pyhdb and everything correctly. However
        the problem I see is that everytime i need to fetch the data it
        comes as a tuple. I want to fetch the data as a pandas
        dataframe. Like in Postgressql if I connect it with Python and
        use an adapter called pysopg2 on the connection object like
        below: 
      `Creating database connection string
        In [9]:
        USER_CRED_FILE = os.path.join(os.path.expanduser('~'),
        '.dslab_user.cred')
        def fetchDBCredentials(dbcred_file=USER_CRED_FILE):
        """
        Read database access credentials from the file in
        $HOME/.ipynb_dslab.cred
        """
        #Read database credentials from user supplied file
        conf = ConfigParser.ConfigParser()
        conf.read(dbcred_file)
        #host, port, user, database, password
        host = conf.get('database_creds','host')
        port = conf.get('database_creds','port')
        user = conf.get('database_creds','user')
        database = conf.get('database_creds','database')
        password = conf.get('database_creds','password')
      #Initialize connection string
conn_str =  """dbname='{database}' user='{user}' host='{host}' port='{port}' password='{password}'""".format(                       
                database=database,
                host=host,
                port=port,
                user=user,
                password=password
        )
return conn_str

      Create a connection object to the database
        In [10]:
        conn = psycopg2.connect(fetchDBCredentials())
      `
      Then I can simply run 
      conn.commit 
      or I can do 
      psql.read_sql(sql,conn) 
      and it would get the result in table format. 
      How do I get that in HANA. Something similar to Pyscopg2 I
        guess?
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly or view it on
          GitHub

**Comment by shabir1** [comment]
Using pyhdb For large data i am getting below error:
('Not able to retrieve data', DatabaseError(u'internal error: Remote execution error exception 1000002: Allocation failed ; $size$=33554432; $name$=itab; $type$=pool; $inuse_count$=13936; $allocated
_size$=5032699992\n for query)
is there any other way to get large bach data from hana. (e.g streaming)
