### ISSUE TITLE
batch insert problem

### ISSUE THREAD

**Issue by hong5698** [SAP/PyHDB#67]
this is python 3.5.1, when try to insert batch data like:
    curs01.execute("""select ID,EN,FR,DE,JA,ZH,KO,ZH_HK,ZH_TW,CJK,SPAIN,POLISH,PT,ITALY,
                    NORWAY,SWEFIN,CP874,CP932,CP936_GB2312_2K,CP950,CP1250,CP1251,
                    CP1252,CP1253,CP1254,CP1256,CP1255,CP1257,CP1258
                    from SAMP_LANG_KEYWORD order by ID """)
    keywords01 = curs01.fetchall()
    for key01 in keywords01:
        cmdstr01 = """ INSERT into 24F3AA18E176403CBF3A6111C2B4DF45.SAMP_LANG_KEYWORD
                    (ID1,EN,FR,DE,JA,ZH,KO,ZH_HK,ZH_TW,CJK,SPAIN,POLISH,PT,ITALY,
                    NORWAY,SWEFIN,CP874,CP932,CP936,CP950,CP1250,CP1251,
                    CP1252,CP1253,CP1254,CP1256,CP1255,CP1257,CP1258) VALUES (
                    :1,:2,:3,:4,:5,:6,:7,:8,:9,:10,
                    :11,:12,:13,:14,:15,:16,:17,:18,:19,:20,
                    :21,:22,:23,:24,:25,:26,:27,:28,:29
                    ) """
        curs02.execute(cmdstr01,[key01[0],key01[1],key01[2],key01[3],key01[4],key01[5],key01[6],key01[7],key01[8],key01[9],
                       key01[10],key01[11],key01[12],key01[13],key01[14],key01[15],key01[16],key01[17],key01[18],key01[19],
                       key01[20],key01[21],key01[22],key01[23],key01[24],key01[25],key01[26],key01[27],key01[28]])

after running above statement, there is no data in the table, I have to add one more line:
curs02.execute('commit')

with above "commit", I could see data, but at the same time, it shows error message like:
Error
Traceback (most recent call last):
  File "C:\Test\Hana\hrtt\test0.py", line 39, in test_hana
    hana_test(curs1)
  File "C:\Test\Hana\hrtt\shared\fun_hrtt.py", line 579, in hana_test
    curs02.execute('commit')
  File "C:\Apps\Python35\lib\site-packages\pyhdb\cursor.py", line 258, in execute
    self._execute_direct(statement)
  File "C:\Apps\Python35\lib\site-packages\pyhdb\cursor.py", line 231, in _execute_direct
    raise InterfaceError("Invalid or unsupported function code received: %d" % function_code)
pyhdb.exceptions.InterfaceError: Invalid or unsupported function code received: 11

not so sure, what is wrong here

**Comment by jarus** [comment]
By default PyHDB doesn't work in `autocommit`-Mode. You have to commit your transaction with `cursor.commit()`.

**Comment by hong5698** [comment]
nice tips, will give a try, thx
