### ISSUE TITLE
close connection problem

### ISSUE THREAD

**Issue by hong5698** [SAP/PyHDB#68]
this is python 3.5.1
work with following sample
    import pyhdb
    connection02 = pyhdb.connect(
        host="ykfl00620460a.amer.global.corp.sap",
        port=30215,
        user="i826608",
        password="Initial1"
    )
    curs02 = connection02.cursor()
    curs02.execute("SELECT 'Hello Python World' FROM DUMMY")
    str1 = curs02.fetchone()[0]
    curs02.close()
    connection02.close()

it would fail with error -
Error
Traceback (most recent call last):
  File "C:\Apps\Python35\lib\site-packages\pyhdb\connection.py", line 107, in __send_message_recv_reply
    _payload = self._socket.recv(header.payload_length - payload.tell())
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Test\Hana\hrtt\test0.py", line 39, in test_hana
    hana_test()
  File "C:\Test\Hana\hrtt\shared\fun_hrtt.py", line 606, in hana_test
    connection02.close()
  File "C:\Apps\Python35\lib\site-packages\pyhdb\connection.py", line 168, in close
    reply = self.send_request(request)
  File "C:\Apps\Python35\lib\site-packages\pyhdb\connection.py", line 84, in send_request
    return self.__send_message_recv_reply(payload.getvalue())
  File "C:\Apps\Python35\lib\site-packages\pyhdb\connection.py", line 121, in __send_message_recv_reply
    raise OperationalError("Lost connection to HANA server (%r)" % error)
pyhdb.exceptions.OperationalError: Lost connection to HANA server (ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

but the following case would work fine:
    import pyhdb
    connection02 = pyhdb.connect(
        host="ykfl00620460a.amer.global.corp.sap",
        port=30215,
        user="i826608",
        password="Initial1"
    )
    curs02 = connection02.cursor()
    curs02.execute("SELECT 'Hello Python World' FROM DUMMY")
    curs02.fetchone()
    curs02.close()
    connection02.close()
- I did not read data with:
  str1 = curs02.fetchone()

**Comment by jarus** [comment]
Looks like your database closed/reject the connection. Do you run the script in parallel? Maybe your account only allow one parallel connection.

**Comment by hong5698** [comment]
no, this is a single app, not in parallel. how can you tell that it allows only one parallel connection? and how/where to change it? thx

**Comment by andrewtmendoza** [comment]
I've encountered this same error and had to place connection.close() in a try/except block.

**Comment by zygimantus** [comment]
I am also facing this issue. Basically if I am commenting this line, issue is not present anymore `connection.close()`.

**Comment by jonbrasher** [comment]
Also facing this issue on one machine and not another. The machine I do not experience the exception is one with SAP HANA client installed. Are there dependencies or imports (maybe even namespace collision) that cause the error not to happen?

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project. Please check active maintained alternative: https://pypi.org/project/hdbcli/
