### ISSUE TITLE
Insert Execution into a series table doesnot work

### ISSUE THREAD

**Issue by jayanthjaiswal** [SAP/PyHDB#7]
Hi all,

If you create a table like this:
Create column table Series ("READING_TYPE_ID" NVARCHAR(10) NOT NULL ,"TIMESTAMP" LONGDATE CS_LONGDATE NOT NULL ,"VALUE" DOUBLE CS_DOUBLE) SERIES (SERIES KEY("READING_TYPE_ID") PERIOD FOR SERIES ("TIMESTAMP") EQUIDISTANT INCREMENT BY INTERVAL .000001 SECOND MISSING ELEMENTS ALLOWED)

And then do insert like this:
insertStmnt = 'insert into ' + table + ' values ' + '( ' + row["READING_TYPE_ID"] + " , '" + row["TIMESTAMP"] + "' , " + row["VALUE"] + ' )'
cursor.execute(insertStmnt)

The statement gets executed with 0 exit code but the value is not inserted. With jaydebeapi and jpype it works though. Fix this.

**Comment by klotz94** [comment]
Hi jayanthjaiswal,

did you call the commit method of the connection object? Auto-commit is deactivated by default.

Best regards

**Comment by jayanthjaiswal** [comment]
Yes, after commiting the data gets inserted. Please mention in README that Auto-commit is deactivated by default.

Regards,
Jayanth
