### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by robertcoon** [SAP/PyHDB#70]
Receiving a interesting error when trying to do a insert into SPS12 from Python 3.5:
Traceback (most recent call last):
  File "C:\Users\sap\Anaconda3\lib\site-packages\pyhdb-0.3.1-py3.5.egg\pyhdb\connection.py", line 108, in __send_message_recv_reply
    _payload = self._socket.recv(header.payload_length - payload.tell())
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Coon_test.py", line 21, in <module>
    connection.close()
  File "C:\Users\sap\Anaconda3\lib\site-packages\pyhdb-0.3.1-py3.5.egg\pyhdb\connection.py", line 168, in close
    reply = self.send_request(request)
  File "C:\Users\sap\Anaconda3\lib\site-packages\pyhdb-0.3.1-py3.5.egg\pyhdb\connection.py", line 84, in send_request
    return self.__send_message_recv_reply(payload.getvalue())
  File "C:\Users\sap\Anaconda3\lib\site-packages\pyhdb-0.3.1-py3.5.egg\pyhdb\connection.py", line 121, in __send_message_recv_reply
    raise OperationalError("Lost connection to HANA server (%r)" % error)
pyhdb.exceptions.OperationalError: Lost connection to HANA server (ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

Any thoughts?

**Comment by jarus** [comment]
Looks like your HANA database closed/reject the connection. Are you able to connect with other clients like the HANA studio?

**Comment by jarus** [comment]
Maybe your user account doesn't have the privileges to open a ODBC/JDBC connection.

**Comment by YEM-1** [comment]
I'm getting the same error.  Let me explain the conditions for my error.
Computer 1:  Running the code in Spyder 3.  No error.
Computer 2: Exact same code in Visual Studio Code.  Stepping through the code shows it is connecting fine.  SQL is executing.  I'm dumping the result set to a CSV.  That is working.  I can step into connection.close() and that works.  But, it will fail on the next line of code after connection.close().

On both computer 1 and computer 2 I do this:
connection.close()
print('done')

Computer 2 fails on the print('done') statement, giving this error:
pyhdb.exceptions.OperationalError: Lost connection to HANA server (ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

So, I don't know if it is something to do with Visual Studio Code editor, or, some other config on Computer 2.  I guess I will have to install Spyder 3 on Computer 2 to eliminate that difference.

**Comment by jarus** [comment]
@YEM-1 What is Spyder 3? I assume you have the same issues as other uses reported in #68 that the close method doesn't handle exceptions well. Please let us merge and continue the discussion in that issue thread.

**Comment by cavemanf16** [comment]
Spyder 3 is an IDE packaged with the Anaconda packaging system. I believe the error may be related to user security being restricted such that even though the connection, Kerberos authentication cannot be completed, and the connection is closed by the remote host. I know my organization has such rules, and this is the error message I receive when trying to connect with my standard account (which is restricted from connecting to HANA via any method other than HANA Studio:

```
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<<<my user directory>>>/workspace/python/connect_to_HANA_test.py", line 24, in <module>
    conn.close()
  File "<<<my user directory>>>\AppData\Local\Continuum\anaconda3\lib\site-packages\pyhdb\connection.py", line 168, in close
    reply = self.send_request(request)
  File "<<<my user directory>>>\AppData\Local\Continuum\anaconda3\lib\site-packages\pyhdb\connection.py", line 84, in send_request
    return self.__send_message_recv_reply(payload.getvalue())
  File "<<<my user directory>>>\AppData\Local\Continuum\anaconda3\lib\site-packages\pyhdb\connection.py", line 121, in __send_message_recv_reply
    raise OperationalError("Lost connection to HANA server (%r)" % error)
pyhdb.exceptions.OperationalError: Lost connection to HANA server (ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<<<my local path>>>/workspace/python/connect_to_HANA_test.py", line 27, in <module>
    write_to_page( "<p>Error: %s</p>" % e )
NameError: name 'write_to_page' is not defined
```

**Comment by YEM-1** [comment]
Hi @cavemanf16 ,
I think your issue is different based on your statement that the issues is with connecting.  We're having no issue connecting, only an issue closing the connection without a traceback.  
For my situation, I just wrap my close.con in a Try: Except: block.  What I noticed is the error is sporadic.  I really don't care of the close method is successful, so the only thing I do is update my ELT log files with "connection closes successfully, job completed" or "connection close failed, job completed".  That way I have some record of it, but functionally the ETL process is the same if the connection close is failing or working.
Also, just thought I'd add, in my situation, we are not using Kerberos for authentication (just user ID and password).  Also, we have no restrictions on ODBC connections to the HANA database.

**Comment by radhikanaikankatte** [comment]
I am getting the same ConnectionRestError as well .

connection.py", line 107, in __send_message_recv_reply
    _payload = self._socket.recv(header.payload_length - payload.tell())
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

Strangely, I see that the connection is indeed established, and the commands are indeed executed on the DB (I see them in the trace). But some go through successfully and some not (for eg: CREATE does result in ta table being created , but INSERT does not insert any values ). I have double checked the queries and they are fine too. For any of these, before I get a response from the HDB, the connection has been reset. 

Could any of you get this issue resolved?

**Comment by zygimantus** [comment]
I am facing the same issue:

> Traceback (most recent call last):
>   File "c:\users\zygimantus\appdata\local\programs\python\python38-32\lib\site-packages\pyhdb\connection.py", line 107, in __send_message_recv_reply
>     _payload = self._socket.recv(header.payload_length - payload.tell())
> ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
