### ISSUE TITLE
Missing support for TEXT datatype?

### ISSUE THREAD

**Issue by swenzel** [SAP/PyHDB#72]
When trying to insert data into a TEXT field I'm getting:

> InterfaceError: Prepared statement parameter datatype not supported: 32

MVE:

``` python
from contextlib import closing
import pyhdb
hanadata = dict(
    user     = '',
    password = '',
    host     = '',
    port     = 30015)

with closing(pyhdb.connect(**hanadata)) as con:
    curs = con.cursor()
    curs.execute('SET SCHEMA MYSCHEMA;')
    curs.execute('CREATE COLUMN TABLE MYTESTTABLE(ID INT PRIMARY KEY, SOMETEXT TEXT);')
    curs.execute('INSERT INTO MYTESTTABLE (ID, SOMETEXT) VALUES (?,?);', [1,'asdf'])
    # won't reach this line
    curs.execute('SELECT * FROM MYTESTTABLE;')
    print(curs.fetchall())
```

**Comment by TwoLaid** [comment]
If you absolutely need support for `TEXT` columns right now, feel free to use our fork at https://github.com/hpi-epic/PyHDB until this has been merged.

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project. Please check active maintained alternative: https://pypi.org/project/hdbcli/
