### ISSUE TITLE
Update INSERT and UPDATE examples in README to show commit invocation

### ISSUE THREAD

**Issue by hsgfan** [SAP/PyHDB#75]
Unfortunately, the README does not display correctly how an insert is performed. Please add the `commit` call inside the code snippet or mention it in the text, as its necessity is not obvious.

**Comment by m-a-leclercq** [comment]
Hi hsgfan, would you mind sharing the correct syntax used to commit a transaction ? Here is pretty much what I have once I am correctly connected : 

cursor = connection.cursor()
cursor.execute("""INSERT INTO "MYSCHEMA"."MYTABLE" VALUES ('mystringvalue','2015-01-01',25);""")
connection.commit 

All commands are successful (If I re execute the second one it tells me I am violating a primary key constraint). The last command outputs <<bound method connection.commit of <Hana connection host =myhost port = myport user = myuser>>

But then nothing happens on the HANA side. 

Any help would be appreciated on how to commit a specific transaction before the README is updated with an example I can understand. 

Thank you

**Comment by TwoLaid** [comment]
I am not sure if that is a typo but to actually call the commit function you need to add the parentheses, so:

```connection.commit()```

Let me know if that helps

**Comment by m-a-leclercq** [comment]
Yep, That was the problem indeed. Thanks!

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project. Please check active maintained alternative: https://pypi.org/project/hdbcli/
