### ISSUE TITLE
Rounding error on Timestamp column

### ISSUE THREAD

**Issue by carlsoane** [SAP/PyHDB#78]
I encountered the error "DatabaseError(u'invalid DATE, TIME or TIMESTAMP value: not a valid millisecond: 60000: type_code=16, index=2',)" when running through the Django tutorial https://docs.djangoproject.com/en/1.10/intro/tutorial02/. Specifically, I encountered it when I executed the instruction: "Question.objects.get(pub_date__year=current_year)". The problem is that that instruction generates a query with two parameters to identify the current year: '2017-01-01 00:00:00',  and '2017-12-31 23:59:59.999999'. The preparation of the second parameter causes the problem. You don't need Django to reproduce the problem, but I mention it because it shows that the bug, though an edge case, unfortunately shows up in a very well travelled place.

The problem is in the handling of microseconds in pyhdb.protocols.types.Timestamp. The 59 seconds and 999999 microseconds of the second parameter is being rounded up to 60000 in the Timestamp.prepare function. 60000 is, of course, an invalid millisecond value. 

I have attached a zip file, sql_parm_test.zip, that containing three files:
- sql_parm_test.sql: This contains the sql needed to run the test.
- sql_parm_test.py: This contains the python test needed to reproduce the problem.
- sql_parm_fix.txt: This is a code snippet that shows the fix that I implemented for my environment.

I am using the following versions of things:
- HANA, express edition 2.00.000.00.1479874437
- python 2.7.10
- pyhdb 0.3.2
- six 1.10.0
For the record, I am using the following Django modules:
- Django 1.10.5
- django-hana 1.1

[sql_parm_test.zip](https://github.com/SAP/PyHDB/files/714693/sql_parm_test.zip)

Regards,

Carl Soane

**Comment by carlsoane** [comment]
Turns out this problem is already addressed in this commit by gbandet: https://github.com/SAP/PyHDB/commit/430d7f2922e409bc338a47f9b34e9de493ed116c
It would be great to get a version pushed up to PyPI that has this fix in it.

Regards,

Carl

**Comment by jarus** [comment]
Fixed in released version 0.3.3. Thank you again for your detailed bug report.
