### ISSUE TITLE
EXECUTION_COUNT in M_SQL_PLAN_CACHE  is not updated

### ISSUE THREAD

**Issue by sgkim126** [SAP/PyHDB#79]
Hi PyHDB folks,

I tried to know the execution time of my query.
I read M_SQL_PLAN_CACHE, because it contains TOTAL_EXECUTION_TIME and EXECUTION_COUNT.

First time I tried below code.
```python
STAT = """SELECT TOTAL_EXECUTION_TIME, EXECUTION_COUNT
FROM M_SQL_PLAN_CACHE
WHERE TO_VARCHAR(STATEMENT_STRING)=:1
AND IS_VALID = 'TRUE'"""

q = 'SELECT * FROM EC_TEST_TABLE'

con = pyhdb.connect(host=HOST, password=PASSWORD, user=USER, port=PORT)
cur = con.cursor()

def fetch(q):
    cur.execute(q, [])
    cur.fetchall()
    cur.execute(STAT, [q])
    return cur.fetchall()
```

A fetch function get execution count and execution time from M_SQL_PLAN_CACHE after executing query and fetching all data.
I thought it would work and it worked if `EC_TEST_TABLE` table does not have lob field.
But if it has a lob field(either NCLob, CLob or Blob) and the table is not empty, the execution count and time does not increases.

In the second try, I closed cursor before read M_SQL_PLAN_CACHE
```python
def cursor_close_and_fetch(q):
    global cur
    cur.execute(q)
    cur.fetchall()
    cur.close()
    cur = con.cursor()
    cur.execute(STAT, [q])
    return cur.fetchall()
```
But it does not worked neither.

Finally, I found a workaround, execution time is updated when the connection is closed. But I think closing cursor should be enough to update execution time.
```python
def connection_close_and_fetch(q):
    global cur, con
    cur.execute(q)
    cur.fetchall()
    cur.close()
    con.close()
    con = pyhdb.connect(host=HOST, password=PASSWORD, user=USER, port=PORT)
    cur = con.cursor()
    cur.execute(STAT, [q])
    return cur.fetchall()
```

**Comment by jarus** [comment]
Actually I don't think we can't fix or change the behaviour as it is internal HANA session and statistic handling. If this feature/metric is critical for you then you should evaluate hdbcli the official support Python Client for SAP HANA. With it and a support contract you can use the normal Product Support process to raise your problem.
