### ISSUE TITLE
Request: Support `qmark` and and `named` as paramstyles

### ISSUE THREAD

**Issue by 0x203** [SAP/PyHDB#8]
Currently, only `format` is supported as a paramstyle. Unfortunately, this is some kind of the opposite from the hdbcli python library from the HANA-Client, which supports `qmark` and `named` as parameter styles. This makes switching unhandy. A possible abstraction from the underlying connector would have to handle this.

I would like to have more paramstyles supported, here.

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project. Please check active maintained alternative: https://pypi.org/project/hdbcli/
