### ISSUE TITLE
Python and HCP Trial connectivity issue. 

### ISSUE THREAD

**Issue by Vigneshbosch** [SAP/PyHDB#86]
I am trying to establish a connection with my HCP trail account from python but facing the below issue:

![capture](https://cloud.githubusercontent.com/assets/19144034/25893969/a9e6ccce-3597-11e7-93f8-db77a6e8da99.PNG)

The code snippet i used to establish this connection is :

import dbapi

conn = dbapi.connect( 'hanatrial.ondemand.com' , 30015, 'p1942054738', 'xxxxxx')

print ( conn.isconnected())

Please note :

- i have placed this code under python folder of hdbclient.

- I have copied these files into the Lib folder of python

            * __init__.py, dbapi.py, resultrow.py

            * pyhdbcli.pdb, pyhdbcli.pyd

Please let me know what am i missing to establish a connection between HCP and python.

**Comment by iivanov-hub** [comment]
Take a look here:

https://blogs.sap.com/2015/04/24/try-hanatrial-using-python-or-nodejs/

**Comment by TwoLaid** [comment]
Please note that this repository is *not* about the HANA connector that ships with HANA, which you seem to be using.

**Comment by Vigneshbosch** [comment]
@iivanov-hub 
Thanks for the response the blog was useful but the open-db-tunnel doesn't provide me with a user name and password. 

![capture2](https://cloud.githubusercontent.com/assets/19144034/25895368/2e47c3ce-359d-11e7-8088-b1f3b696c859.PNG)

Please let me know if i am missing something ? 

@TwoLaid 
I even tried with the pyhdb library still no luck. The connection gets timed out.

![untitled](https://cloud.githubusercontent.com/assets/19144034/25895564/09dc9f04-359e-11e7-9eb7-ae85c3b8af56.png)

**Comment by iivanov-hub** [comment]
Once you have tunnel up and running, you have to use your database user and password, SYSTEM for example. host is "localhost" and port is 3015, based on output from your command output.

**Comment by TwoLaid** [comment]
I've never worked with a HCP trial instance, but maybe refer to this thread: https://github.com/SAP/node-hdb/issues/1 

It is for the NodeJS connector but the logic might be applicable here as well

**Comment by jarus** [comment]
Sorry for the late response. If the issue still persist then please feel free to reopen the issue. I would also recommend to contact the HCP/SCP support as it looks like a problem related with the HCP/SCP proxy.
