### ISSUE TITLE
Need to insert 10 million record from Python into Hana Table ..... 

### ISSUE THREAD

**Issue by Vigneshbosch** [SAP/PyHDB#91]
Hi All, 

Please suggest a best way to insert around 10 million into Hana Table . Is it possible to pass a data frame as a  parameter for a Stored procedure call ?? 

Thanks in advance 

Regards 
Vignesh J

**Comment by jarus** [comment]
Hi, there is no dedicated support of panda's dataframes. For inserting 10 million reconds, I would also recommend to evaluate HANA's [IMPORT FROM](https://help.sap.com/viewer/bed8c14f9f024763b0777aa72b5436f6/2.0.02/en-US/22e7b35dd77744fa98225c1801ef4f31.html) feature.
