### ISSUE TITLE
'Invalid column name' error when using max() in query

### ISSUE THREAD

**Issue by bpmcl** [SAP/PyHDB#92]
When using the max() function in a query, I receive the following error:

```
>>> cursor.execute('SELECT packages.id AS packages_id, packages.name AS packages_name,
packages.version AS packages_version, packages.enabled AS packages_enabled,
max(packages.version) AS max_1 FROM packages')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python3.5/site-packages/pyhdb/cursor.py", line 258, in execute
    self._execute_direct(statement)
  File "/lib/python3.5/site-packages/pyhdb/cursor.py", line 217, in _execute_direct
    reply = self.connection.send_request(request)
  File "/lib/python3.5/site-packages/pyhdb/connection.py", line 84, in send_request
    return self.__send_message_recv_reply(payload.getvalue())
  File "/lib/python3.5/site-packages/pyhdb/connection.py", line 124, in __send_message_recv_reply
    return ReplyMessage.unpack_reply(header, payload)
  File "/lib/python3.5/site-packages/pyhdb/protocol/message.py", line 92, in unpack_reply
    segments=tuple(ReplySegment.unpack_from(payload, expected_segments=header.num_segments)),
  File "/lib/python3.5/site-packages/pyhdb/protocol/segments.py", line 152, in unpack_from
    raise error.parts[0].errors[0]
pyhdb.exceptions.DatabaseError: invalid column name: The column 'PACKAGES.ID' is invalid in
the select list because the GROUP BY clause or an aggregation function does not contain it:
line 1 col 8 (at pos 7)
```

The same query works correctly without the function, as does using it without selecting any other columns. Am I doing something wrong, or is this a bug?

**Comment by TwoLaid** [comment]
This is not a bug, but simply an invalid SQL query.

Aggregate functions like `MAX` either need a `GROUP BY` statement or it will just calculate the maximum of the whole table. In the latter case, however, you cannot project any other non-aggregated columns.

In your case, you have two options:

1) Use two queries. One to `SELECT packages.id AS packages_id, packages.name AS packages_name,
packages.version AS packages_version, packages.enabled AS packages_enabled` and one to `SELECT max(packages.version) AS max_1`
2) If you *need* this to be in one query result, this might work:

```
SELECT 
    packages.id AS packages_id, 
    packages.name AS packages_name, 
    packages.version AS packages_version, 
    packages.enabled AS packages_enabled, 
    (SELECT max(packages.version) AS max_1 FROM packages) AS max_1
FROM packages
```

**Comment by bpmcl** [comment]
I figured it may have been problematic to do it this way. I have fixed it by using the max query to get a value for version that is used as WHERE criteria in the 2nd query. Thanks for the response!
