### ISSUE TITLE
How to Setup SAML authentication Method

### ISSUE THREAD

**Issue by Vigneshbosch** [SAP/PyHDB#96]
Hi @jarus 

Can you please help me on how to setup SAML authentication method to establish a connection between Python application running in Hana VM and the Hana Database in the SAP Cloud Platform. 

Thanks 
Vignesh

**Comment by jarus** [comment]
SAML authentication isn't planed for PyHDB but the hdbcli Python interface from HANA 2 SPS 2 which provides the same DBAPI allows SAML authentication.

Regards,
Christoph
