### ISSUE TITLE
Missing HANA Table Headers

### ISSUE THREAD

**Issue by quincymac** [SAP/PyHDB#99]
Hi there,

I am able to run queries as follows:

```
cursor.execute('select top 100 * from "tbl_Q1"')
ss = cursor.fetchall()
```
However I can't determine how to get the column headers for my query.
Any help would be much appreciated!

Basically I want to return the result with the table headers/column names

**Comment by jarus** [comment]
`cursor.description` should contain the data that you search. It is part of [PEP 248](https://www.python.org/dev/peps/pep-0248/#cursor-objects).

**Comment by quincymac** [comment]
Thanks Jarus that was it!!

**Comment by mbenetti** [comment]
Good morning, I get the name of the columm with some extra information, how shoud I ask for the description to get only the name? 

Thank you in advance for the help.

Best regards.
